services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: uni-chat-api
    restart: unless-stopped

    ports:
      - "8080:8080"

    env_file:
      - .env
   
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ENABLE_DOCS: ${ENABLE_DOCS}
      Mongo__ConnectionString: ${MONGO_CONNECTION_STRING}
      Mongo__Database: ${MONGO_DATABASE}
      Redis__ConnectionString: ${REDIS_CONNECTION_STRING}
      RabbitMQ__ConnectionString: ${RABBITMQ_CONNECTION_STRING}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Cloudinary__CloudName: ${CLOUDINARY_CLOUD_NAME}
      Cloudinary__ApiKey: ${CLOUDINARY_API_KEY}
      Cloudinary__ApiSecret: ${CLOUDINARY_API_SECRET}
      ASPNETCORE__ENVIRONMENT: Production
      ENABLE__DOCS: ${ENABLE_DOCS}


    depends_on:
      mongodb:
        condition: service_healthy

      redis:
        condition: service_started

      rabbitmq:
        condition: service_healthy

      seq:
        condition: service_started

    networks:
      - backend-net

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    volumes:
      - mongo-data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - backend-net

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - backend-net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - backend-net

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINUSERNAME: ${SEQ_ADMIN}
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_ADMIN_PASSWORD}
      TZ: America/Bogota

    ports:
      - "5341:80"

    volumes:
      - seq-data:/data

    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  rabbitmq-data:
  seq-data: