services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uni-chat-api
    restart: unless-stopped
    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      Mongo__ConnectionString: ${MONGO_CONNECTION_STRING}
      Mongo__Database: ${MONGO_DATABASE}

      Redis__ConnectionString: ${REDIS_CONNECTION_STRING}
      RabbitMQ__ConnectionString: ${RABBITMQ_CONNECTION_STRING}

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}

      RefreshToken__ExpireDays: ${REFRESH_EXPIRE_DAYS}

      Cloudinary__CloudName: ${CLOUDINARY_CLOUD_NAME}
      Cloudinary__ApiKey: ${CLOUDINARY_API_KEY}
      Cloudinary__ApiSecret: ${CLOUDINARY_API_SECRET}

    depends_on:
      rabbitmq:
        condition: service_started
      mongodb:
        condition: service_started
      redis:
        condition: service_started

    networks:
      - backend-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - backend-net

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - backend-net

networks:
  backend-net: